[package]
name = "selectme-macros"
version = "0.2.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/udoprog/selectme"
homepage = "https://github.com/udoprog/selectme"
documentation = "https://docs.rs/selectme"
description = """
A fast and fair select! macro for asynchronous Rust.
"""
categories = ["asynchronous", "concurrency"]

[lib]
proc-macro = true
