name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: ['1.56', stable]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.rust}}
    - run: cargo build -p selectme -p selectme-macros
    - run: cargo test --workspace --all-targets --all-features
      if: matrix.rust == 'stable'
    - run: cargo test --workspace --all-targets --no-default-features
      if: matrix.rust == 'stable'
    - run: cargo test --workspace --doc --all-features
      if: matrix.rust == 'stable'

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.68
      with:
        components: clippy
    - run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --check --all

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
    - run: cargo doc --workspace --all-features
      env:
        RUSTFLAGS: --cfg selectme_docsrs
        RUSTDOCFLAGS: --cfg selectme_docsrs
